server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: djl-docs-reader

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_doc_reader_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 0123456789

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

ocr:
  tessdata:
    path: "C:\\Program Files\\Tesseract-OCR\\tessdata"
  language: vie
  psm: 6
  oem: 1